spring:
  profiles:
    active: dev
server:
  port: 8888

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: test123456
  config:
    activate:
      on-profile: dev



---
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  config:
    activate:
      on-profile: dev

